services:
  - type: web 
    name: testCloudApp
    runtime: node
    repo: https://github.com/Celina-cbn/cloudTest.git
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-name
          property: connectionString

databases:
  - name: db-name
    plan: free
    region: frankfurt
