services:
  - type: web 
    plan: starter
    name: testCloudApp
    repo: https://github.com/Celina-cbn/cloudTest.git
    buildCommand: npm install
    startCommand: node app.js
    # env: production
