services:
  - type: static 
    plan: starter
    name: testCloudApp
    plan: free
    repo: https://github.com/Celina-cbn/cloudTest.git
    buildCommand: npm run build
    # startCommand: ????
    env: production

