services:
  - type: web 
    plan: starter
    name: testCloudApp
    runtime: node
    repo: https://github.com/Celina-cbn/cloudTest.git
    buildCommand: npm install
    startCommand: npm run start
    env: production
